### ISSUE TITLE
Wait until we load your vehicle. 

### ISSUE THREAD

**Issue by akshaygitty** [Duart3x/d3x_vehicleshop#9]
"Wait until we load your vehicle. " This is shown in mythic notification and it strucks there. The vehicle wont be spawned even if we wait for a long time. Can you please solve this issue?

**Comment by CraymHD** [comment]
# You have 2 option : 
- Add a script which load the airport because it's too far and that's why nothing happens.
- Change the coord, like near of the car dealer. if you put the shop in the **Premium Deluxe Motorsport** then you can take my coords if you want : 
Line 91 in   `\resources\d3x_vehicleshop\client\main.lua` : 

> ESX.Game.SpawnVehicle(model, vector3(8, -1105.6, 38.15), 70, function(vehicle)

**Comment by ItzTrivial** [comment]
Hey there. Its the first time Im trying to help someone on github, because Im a rookie too, but I solved it with some help. 
The 2 options CraymHD said are possible would seriously solve the problem, but noone wants random people to testdrive cars and teleport on a public street, right? So basically you need to make the player teleport to the airport first. So thats how the code is supposed to look like for it to work. As you can see the player gets teleported, after that the car spawned and the player put into it. I hope I was able to help you.

`RegisterNUICallback('TestDrive', function(data, cb) 
	SetNuiFocus(false, false)
	
	local model = data.model
	local playerPed = PlayerPedId()
	local playerpos = GetEntityCoords(playerPed)
	
	IsInShopMenu = false
	exports['mythic_notify']:PersistentHudText('start','inform','vermelho',_U('wait_vehicle'))
		SetEntityCoords(playerPed, -1733.25, -2901.43, 13.94)
                SetEntityHeading(playerPed, 330)
	ESX.Game.SpawnVehicle(model, vector3(-1733.25, -2901.43, 13.94), 330, function(vehicle)
		exports['mythic_notify']:PersistentHudText('end','inform')
		TaskWarpPedIntoVehicle(playerPed, vehicle, -1)
		SetVehicleNumberPlateText(vehicle, "TEST")
		ESX.ShowNotification(_U('testdrive_notification',testdrive_timer))
		Citizen.CreateThread(function () 
			local counter = testdrive_timer
			
			while counter > 0 do 
				exports['mythic_notify']:DoCustomHudText('branco', _U('testdrive_timer',counter),700)
				counter = counter -1
				Citizen.Wait(1000)
			end
			DeleteVehicle(vehicle)
			SetEntityCoords(playerPed, playerpos, false, false, false, false)

			ESX.ShowNotification(_U('testdrive_finished'))
		end)

	end)
end)`
